#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WhoAmI.Droid.Resource", IsApplication=true)]

namespace WhoAmI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int eac_image = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int funcionario = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int login_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030001
			public const int CustomActionBarTheme = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int CustomTheme = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int MyActionBar = 2130903042;
			
			// aapt resource value: 0x7f030004
			public const int MyActionBar_ActionBar_TitleTextStyle = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int MyActionBar_ActionBarStyle = 2130903043;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
